USE videomino

-- FUNÇÃO QUE CALCULA O TOTAL QUE A VIDEOMINO
-- FATUROU NUM DADO PERÍODO DE TEMPO

DELIMITER $$
CREATE FUNCTION calcularTotalFaturado (data1 DATE, data2 DATE) RETURNS FLOAT DETERMINISTIC
BEGIN
	DECLARE total DECIMAL(10,2);
	SET total = (SELECT SUM(v.preco_final)
				FROM Venda AS v
                WHERE v.data BETWEEN data1 AND data2);
	RETURN total;
END $$
DELIMITER ;

-- SELECT CALCULARTOTALFATURADO('2022-01-01', '2023-07-01');